# fly.toml app configuration file generated for pdhdata on 2023-05-24T04:34:02-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pdhdata"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"
console_command = "poetry run python _manage.py shell"

[experimental]
  auto_rollback = true

[deploy]
  release_command = "poetry run python _manage.py migrate"

[env]
  DJANGO_SETTINGS_MODULE = "smallformats.settings"
  SMALLFORMATS_NAME = "PDHdata"

[processes]
  app = "poetry run daphne -b 0.0.0.0 -p 8080 smallformats.asgi:application"
  cron = "supercronic /app/scheduled/crontab"

[http_service]
  internal_port = 8080
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

  [http_service.http_options]
    idle_timeout = 600

# health checks come with an incorrect HTTP_HOST header
# (an IPv4 address), probably due to something with https/http.
#
# [[http_service.checks]]
#   interval = "30s"
#   timeout = "2s"
#   grace_period = "5s"
#   restart_limit = 0

[[statics]]
  guest_path = "/fake"
  url_prefix = "/fake"
