[tool.poetry]
name = "smallformats"
version = "0.5.0"
description = "A deck-stats site for smaller MtG formats like PDH"
authors = ["Matt Cooper <vtbassmatt@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^4.1.2"
dj-database-url = "^2.1.0"
daphne = "^4.1.2"
psycopg2-binary = "^2.9.5"
markdown = "^3.6"
httpx = "^0.27.0"
json-stream = "^2.3.2"
django-debug-toolbar = "^4.3.0"
django-htmx = "^1.17.3"
django-cache-url = "^3.4.5"
whitenoise = "^6.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
