[tool.poetry]
name = "smallformats"
version = "0.1.0"
description = "A deck-stats site for smaller MtG formats like PDH"
authors = ["Matt Cooper <vtbassmatt@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.1.2"
dj-database-url = "^1.0.0"
daphne = "^4.0.0"
psycopg2-binary = "^2.9.5"
djangorestframework = "^3.14.0"
markdown = "^3.4.1"
django-filter = "^22.1"
httpx = "^0.23.0"
json-stream = "^2.0.3"
django-debug-toolbar = "^3.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
