# Generated by Django 4.1.2 on 2022-11-10 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawl_start_time', models.DateTimeField()),
                ('search_back_to', models.DateTimeField(blank=True, null=True)),
                ('target', models.IntegerField(choices=[(0, 'Unknown/other'), (1, 'Archidekt')])),
                ('state', models.IntegerField(choices=[(0, 'Not Started'), (1, 'Fetching Decks'), (2, 'Done Fetching Decks'), (3, 'Fetching Decklists'), (4, 'Done Fetching Decklists'), (5, 'Complete'), (98, 'Cancelled'), (99, 'Error')])),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeckCrawlResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('updated_time', models.DateTimeField()),
                ('got_cards', models.BooleanField(default=False)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decklist.deck')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_results', to='crawler.crawlrun')),
            ],
        ),
    ]
