# Generated by Django 4.1.2 on 2022-11-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrun',
            name='next_fetch',
            field=models.URLField(blank=True),
        ),
    ]
