# Generated by Django 4.1.2 on 2022-10-31 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_add_crawl_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawl_start_time', models.DateTimeField()),
                ('target', models.IntegerField(choices=[(0, 'Unknown/other'), (1, 'Archidekt')])),
                ('state', models.IntegerField(choices=[(0, 'Not Started'), (1, 'Fetching Decks'), (2, 'Done Fetching Decks'), (3, 'Fetching Decklists'), (4, 'Done Fetching Decklists'), (5, 'Complete'), (98, 'Cancelled'), (99, 'Error')])),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='deckcrawlresult',
            name='crawl_time',
        ),
        migrations.AddField(
            model_name='deckcrawlresult',
            name='run',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='deck_results', to='crawler.crawlrun'),
            preserve_default=False,
        ),
    ]
