# Generated by Django 4.1.2 on 2022-11-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_add_crawl_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrun',
            name='search_back_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
