# Generated by Django 4.1.2 on 2022-11-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_decouple_runs_from_decklist_fetches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlrun',
            name='target',
            field=models.IntegerField(choices=[(0, 'Unknown/other'), (1, 'Archidekt'), (2, 'Moxfield')]),
        ),
        migrations.AlterField(
            model_name='deckcrawlresult',
            name='target',
            field=models.IntegerField(choices=[(0, 'Unknown/other'), (1, 'Archidekt'), (2, 'Moxfield')], default=0),
        ),
    ]
