# Generated by Django 4.1.2 on 2022-11-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_add_moxfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckcrawlresult',
            name='fetchable',
            field=models.BooleanField(default=True),
        ),
    ]
