# Generated by Django 4.1.3 on 2022-12-11 12:33

from django.db import migrations


# thanks to https://blog.theletstream.com/recursive-tree-querying-in-django-using-common-table-expressions-64bc00001948
# for the intro to recursive CTEs
def get_all_from_first_line(Model, first_line):
    ids = []
    table_name = Model._meta.db_table
    query = (
        "WITH RECURSIVE children (id) AS ("
        f"  SELECT {table_name}.id FROM {table_name} WHERE id = {first_line.id}"
        "  UNION ALL"
        f"  SELECT {table_name}.id FROM children, {table_name}"
        f"  WHERE {table_name}.follows_id = children.id"
        ")"
        f"SELECT {table_name}.id "
        f"FROM {table_name}, children WHERE children.id = {table_name}.id "
    )
    ids = Model.objects.raw(query)
    return Model.objects.filter(id__in=[obj.id for obj in ids])


def port_logs(apps, schema_editor):
    LogStart = apps.get_model('crawler', 'LogStart')
    LogEntry = apps.get_model('crawler', 'LogEntry')
    first_lines = (
        LogEntry.objects
        .filter(follows=None)
    )
    for first_line in first_lines:
        ls = LogStart(created=first_line.created, text=first_line.text)
        ls.save()
        lines = get_all_from_first_line(LogEntry, first_line)
        lines.update(parent=ls)


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0008_logstart'),
    ]

    operations = [
        migrations.RunPython(port_logs, lambda _1, _2: ...)
    ]
