# Generated by Django 4.1.3 on 2022-12-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0009_port_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='follows',
        ),
        migrations.AlterField(
            model_name='logstart',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='logstart',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
