# Generated by Django 4.1.2 on 2022-11-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='type_line',
            field=models.CharField(max_length=100),
        ),
    ]
