# Generated by Django 4.1.2 on 2022-10-30 14:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('decklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('identity_w', models.BooleanField(default=False, verbose_name='is W')),
                ('identity_u', models.BooleanField(default=False, verbose_name='is U')),
                ('identity_b', models.BooleanField(default=False, verbose_name='is B')),
                ('identity_r', models.BooleanField(default=False, verbose_name='is R')),
                ('identity_g', models.BooleanField(default=False, verbose_name='is G')),
                ('ever_common', models.BooleanField(default=False)),
                ('ever_uncommon', models.BooleanField(default=False)),
                ('can_be_pdh_commander', models.BooleanField(default=False, verbose_name='can be PDH commander')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source', models.IntegerField(choices=[(0, 'Unknown Other'), (1, 'Archidekt')])),
                ('source_id', models.CharField(blank=True, max_length=20)),
                ('source_link', models.URLField(blank=True)),
                ('creator_display_name', models.CharField(max_length=50)),
                ('ingested_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CardInDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pdh_commander', models.BooleanField(default=False, verbose_name='is PDH commander')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deck_list', to='decklist.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_list', to='decklist.deck')),
            ],
        ),
    ]
