# Generated by Django 4.1.2 on 2022-11-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decklist', '0002_increase_typeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printing',
            name='set_code',
            field=models.CharField(max_length=10),
        ),
    ]
