# Generated by Django 4.1.2 on 2022-11-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decklist', '0003_setcode_embiggen'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='pdh_legal',
            field=models.BooleanField(default=False, verbose_name='is PDH-legal'),
        ),
    ]
