# Generated by Django 4.1.2 on 2022-10-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decklist', '0003_fix_human_label'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='deck',
            constraint=models.UniqueConstraint(fields=('source', 'source_id'), name='one_entry_per_deck'),
        ),
    ]
