# Generated by Django 4.1.2 on 2022-11-18 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decklist', '0004_add_legality'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='editorial_printing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_showings', to='decklist.printing'),
        ),
    ]
