# Generated by Django 4.1.2 on 2022-11-19 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decklist', '0005_add_editorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printing',
            name='is_highres',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='is_paper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='printing',
            name='release_date',
            field=models.DateField(default=datetime.date(1993, 8, 5)),
        ),
    ]
