# Generated by Django 4.1.2 on 2022-11-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decklist', '0006_add_set_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='can_be_pdh_commander',
        ),
        migrations.RemoveField(
            model_name='card',
            name='ever_common',
        ),
        migrations.RemoveField(
            model_name='card',
            name='ever_uncommon',
        ),
        migrations.AddField(
            model_name='card',
            name='type_line',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='printing',
            name='rarity',
            field=models.CharField(choices=[('C', 'common'), ('U', 'uncommon'), ('R', 'rare'), ('S', 'special'), ('M', 'mythic'), ('B', 'bonus')], default=None, max_length=1),
            preserve_default=False,
        ),
    ]
