# Generated by Django 4.1.2 on 2022-11-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decklist', '0006_image_improvements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='source',
            field=models.IntegerField(choices=[(0, 'Unknown/other'), (1, 'Archidekt'), (2, 'Moxfield')]),
        ),
        migrations.AlterField(
            model_name='deck',
            name='source_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
