# Generated by Django 4.1.2 on 2022-11-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decklist', '0007_rarity_typeline_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='scryfall_uri',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='image_uri',
            field=models.URLField(blank=True),
        ),
    ]
