# Generated by Django 4.1.3 on 2022-12-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decklist', '0008_sitestat'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='partner_type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'keyword Partner'), (10, 'choose a Background'), (11, 'Background'), (100, 'Blaring Captain/Recruiter'), (101, 'Chakram Retriever/Slinger'), (102, 'Impetuous Protege/Proud Mentor'), (103, 'Soulblade Corrupter/Renewer'), (104, 'Ley/Lore Weaver')], default=0),
        ),
    ]
