# Generated by Django 4.1.3 on 2022-12-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decklist', '0008_sitestat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='source',
            field=models.IntegerField(choices=[(0, 'Unknown/other'), (1, 'Archidekt'), (2, 'Moxfield'), (3, 'TappedOut')]),
        ),
    ]
