# Generated by Django 4.1.3 on 2022-12-25 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decklist', '0010_commander'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='commander',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decks', to='decklist.commander'),
        ),
    ]
