# Generated by Django 4.1.3 on 2022-12-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decklist', '0011_link_deck_to_commander'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cardindeck',
            index=models.Index(fields=['deck', 'card'], name='decklist_ca_deck_id_0db4c9_idx'),
        ),
        migrations.AddIndex(
            model_name='deck',
            index=models.Index(fields=['pdh_legal'], name='decklist_de_pdh_leg_540217_idx'),
        ),
    ]
