# Generated by Django 4.1.3 on 2022-12-31 21:46

from django.db import migrations
import uuid


def populate_cmdr_ids(apps, schema_editor):
    Commander = apps.get_model('decklist', 'Commander')
    for cmdr in Commander.objects.all():
        name = str(cmdr.commander2.id) if cmdr.commander2 else ''
        cmdr.sfid = uuid.uuid5(cmdr.commander1.id, name)
        cmdr.save()


class Migration(migrations.Migration):

    dependencies = [
        ('decklist', '0013_create_cmdr_id'),
    ]

    operations = [
        migrations.RunPython(populate_cmdr_ids, migrations.RunPython.noop)
    ]
