# Generated by Django 4.1.3 on 2022-12-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decklist', '0014_populate_cmdr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commander',
            name='sfid',
            field=models.UUIDField(unique=True, verbose_name='SmallFormats ID'),
        ),
    ]
