# Generated by Django 4.1.3 on 2023-01-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decklist', '0017_example_tribes'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='keywords',
            field=models.JSONField(default=list),
        ),
    ]
