# Generated by Django 4.1.3 on 2023-01-02 19:32

from django.db import migrations


def add_sample_themes(apps, schema_editor):
    Theme = apps.get_model('decklist', 'Theme')
    # note 1: filter_type='K' corresponds to Theme.Type.KEYWORD.
    # note 2: like tribal, thresholds have been tuned based on eyeballing 2023-01-02
    # data. They'll need tweaking over time.
    Theme.objects.bulk_create(
        [
            Theme(display_name='Deathtouch', filter_text='Deathtouch', slug='deathtouch', card_threshold=12, filter_type='K'),
            Theme(display_name='Defender', filter_text='Defender', slug='defender', filter_type='K'),
            Theme(display_name='Equipment', filter_text='Equip', slug='equipment', deck_threshold=20, filter_type='K'),
            Theme(display_name='Flying', filter_text='Flying', slug='flying', filter_type='K'),
            Theme(display_name='Infect', filter_text='Infect', slug='infect', card_threshold=12, filter_type='K'),
            Theme(display_name='Kicker', filter_text='Kicker', slug='kicker', card_threshold=12, filter_type='K'),
            Theme(display_name='Landfall', filter_text='Landfall', slug='landfall', card_threshold=12, filter_type='K'),
            Theme(display_name='Lifelink', filter_text='Lifelink', slug='lifelink', card_threshold=12, filter_type='K'),
            Theme(display_name='Menace', filter_text='Menace', slug='menace', card_threshold=12, filter_type='K'),
        ],
        ignore_conflicts=True,
    )

class Migration(migrations.Migration):

    dependencies = [
        ('decklist', '0018_card_keywords'),
    ]

    operations = [
        migrations.RunPython(add_sample_themes, migrations.RunPython.noop),
    ]
