# Generated by Django 4.1.3 on 2023-01-15 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decklist', '0019_example_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='SynergyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synergy_scores', to='decklist.card')),
                ('commander', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synergy_scores', to='decklist.commander')),
            ],
        ),
        migrations.AddConstraint(
            model_name='synergyscore',
            constraint=models.UniqueConstraint(fields=('commander', 'card'), name='commander_card', violation_error_message='Commander + card is not unique'),
        ),
    ]
