# Generated by Django 4.1.3 on 2023-01-21 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decklist', '0020_synergyscore_synergyscore_commander_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_deck_count', models.IntegerField()),
                ('total_deck_count', models.IntegerField()),
                ('commander', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_results', to='decklist.commander')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='decklist.theme')),
            ],
        ),
        migrations.AddConstraint(
            model_name='themeresult',
            constraint=models.UniqueConstraint(fields=('theme', 'commander'), name='theme_commander', violation_error_message='Commander + theme is not unique'),
        ),
    ]
