# Generated by Django 4.1.3 on 2023-02-18 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decklist', '0021_themeresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopCardView',
            fields=[
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='+', serialize=False, to='decklist.card')),
                ('num_decks', models.IntegerField()),
                ('rank', models.IntegerField()),
            ],
            options={
                'ordering': ['rank'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TopLandCardView',
            fields=[
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='+', serialize=False, to='decklist.card')),
                ('num_decks', models.IntegerField()),
                ('rank', models.IntegerField()),
            ],
            options={
                'ordering': ['rank'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TopNonLandCardView',
            fields=[
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='+', serialize=False, to='decklist.card')),
                ('num_decks', models.IntegerField()),
                ('rank', models.IntegerField()),
            ],
            options={
                'ordering': ['rank'],
                'abstract': False,
                'managed': False,
            },
        ),
    ]
