# Generated by Django 4.1.3 on 2023-02-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decklist', '0023_top_card_materialized_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='scryfall_uri',
            field=models.URLField(max_length=300),
        ),
    ]
