# Generated by Django 5.0.4 on 2024-11-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decklist', '0024_alter_card_scryfall_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='filter_type',
            field=models.CharField(choices=[('T', 'typal'), ('K', 'keyword')], max_length=1),
        ),
    ]
